# Generated by Django 5.2.7 on 2026-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblgallery',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tblgallery',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tblgallery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tblgallery',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
