# Generated by Django 5.2.7 on 2026-09-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblgallery_description_tblgallery_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblgallery',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
