# Generated by Django 5.2.7 on 2026-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tblgallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('guests', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
