# Generated by Django 5.2.7 on 2026-09-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tblContact',
            new_name='tblreservation',
        ),
    ]
