# Generated by Django 5.2.7 on 2026-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_tblcontact_tblreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('Message', models.TextField(blank=True)),
            ],
        ),
    ]
