# Generated by Django 5.2.7 on 2026-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tblcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Food_quality', models.CharField(max_length=10)),
                ('Services', models.CharField(max_length=10)),
                ('Feedback', models.TextField(blank=True)),
                ('recommend', models.CharField(max_length=10)),
            ],
        ),
    ]
