# Generated by Django 5.2.7 on 2026-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tblreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblreview',
            name='Image',
            field=models.ImageField(null=True, upload_to='static/picture/'),
        ),
    ]
