# Generated by Django 5.2.7 on 2026-09-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_tblreview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreview',
            name='Food_quality',
        ),
        migrations.RemoveField(
            model_name='tblreview',
            name='Services',
        ),
    ]
