# Generated by Django 5.2.7 on 2026-09-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_tblreview_food_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tblreview',
            name='recommend',
        ),
    ]
