# Generated by Django 5.2.7 on 2026-09-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_tblreview_email_remove_tblreview_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbllogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
