# Generated by Django 5.2.7 on 2026-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_tbllogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbllogin',
            name='Full_Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbllogin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
