# Generated by Django 5.2.7 on 2026-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_tbllogin_full_name_alter_tbllogin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbllogin',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
