# Generated by Django 5.2.7 on 2026-09-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_tbllogin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=15, null=True)),
                ('Image', models.ImageField(null=True, upload_to='static/picture/')),
                ('Address', models.TextField(blank=True)),
            ],
        ),
    ]
