# Generated by Django 5.2.7 on 2026-09-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tblregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
