# Generated by Django 5.2.7 on 2026-09-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_tblregister_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbllogin',
            name='Full_Name',
        ),
        migrations.AddField(
            model_name='tbllogin',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
